### ISSUE TITLE
Package add button message not changed

### ISSUE THREAD

**Issue by Kieaer** [kurotu/tiny_vcc#8]
![image](https://github.com/kurotu/tiny_vcc/assets/44261958/52a34f3c-ac9b-41d2-a0fb-7a0cdd4254c4)
Before click = After click

**Comment by kurotu** [comment]
I'm not sure what version of SDK you are using (please use the issue template), UdonSharp and ClientSim are now included in world SDK since 3.4.0. So you don't have to add UdonSharp to the project.

The problem is Tiny VCC doesn't support the latest spec of VCC yet, but I believe you can use your project as is.
